sudo: required

language: cpp

compiler:
  - gcc
  # - clang

addons:
 apt:
  sources:
   - boost-latest
   - ubuntu-toolchain-r-test
  packages:
   - g++-5
   - wget
   - libboost1.55-all-dev
   - python-pip

cache:
 - apt

install:
  - pip install conan
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
  - git clone https://github.com/memsharded/conan-premake.git
  - cd conan-premake && conan export . memsharded/testing
  - conan install . --build PremakeGen --build=missing
  - wget https://dl.influxdata.com/influxdb/releases/influxdb-1.2.4_linux_amd64.tar.gz
  - tar xvfz influxdb-1.2.4_linux_amd64.tar.gz
  - premake/premake5-64 gmake

script:
  - CXX="g++-5" make -C build/linux/gmake config=release_x64
  - /bin/bash -c "./src/script/test.sh bin/linux/gmake/x64/Release"
